//! Floo CLI entry point.

mod agent_setup;
mod paths;
mod registry;
mod scanner;

use std::io;
use std::process::ExitCode;

use clap::error::{ContextKind, ContextValue, ErrorKind};
use clap::{CommandFactory, FromArgMatches, Parser, Subcommand};
use clap_complete::Shell;
use registry::FlooError;
use serde::Serialize;

const VERSION: &str = env!("CARGO_PKG_VERSION");

/// The top-level help block. Kept as a static string so `floo`, `floo -h`, and
/// `floo --help` all render the exact same tailored overview.
const TOP_HELP: &str = "usage: floo <command> [options]

commands:
  version                Print floo version
  list                   Show all claims and listening status
                           --json
  claim <service>        Claim (or fetch) a port for a service
                           --prefer <port>
                           --json
  release <service>      Release a claim
  release --all          Release every claim
  gc                     Reclaim stale claims
                           --older-than <duration> (default '-7 days')
                           --dry-run
  agent-setup            Write the floo instruction into ~/.claude/CLAUDE.md
  completions <shell>    Print a shell completion script (bash, zsh, fish)

options:
  --db <path>            Use this registry file instead of the XDG default
  --version, -V          Print version and exit
  -h, --help             Show this help

The registry path is resolved as: --db <path> if given, else the FLOO_DB
environment variable if set, else the XDG default
($XDG_STATE_HOME/floo/registry.db or ~/.local/state/floo/registry.db).";

/// JSON shape emitted by `claim --json`: the claim record plus `was_new`.
#[derive(Serialize)]
struct ClaimJson<'a> {
    #[serde(flatten)]
    claim: &'a registry::Claim,
    was_new: bool,
}

/// JSON shape emitted by `list --json`: each claim record plus live
/// `listening` status observed at print time.
#[derive(Serialize)]
struct ListEntryJson<'a> {
    #[serde(flatten)]
    claim: &'a registry::Claim,
    listening: bool,
}

/// Top-level CLI. Per-subcommand `--help` is generated by clap; the top-level
/// help is overridden with `TOP_HELP` at parse time.
#[derive(Parser)]
#[command(name = "floo", version, disable_help_subcommand = true)]
struct Cli {
    /// Use this registry file instead of the XDG default.
    #[arg(long, global = true, value_name = "path")]
    db: Option<String>,

    #[command(subcommand)]
    command: Option<Command>,
}

#[derive(Subcommand)]
enum Command {
    /// Claim (or fetch) a port for a service.
    Claim {
        /// Service label, for example web, api, storybook.
        service: Option<String>,
        /// Preferred port to try first.
        #[arg(long, value_name = "port")]
        prefer: Option<u16>,
        /// Emit the claim as JSON instead of a bare port.
        #[arg(long)]
        json: bool,
    },
    /// Release a claim, or every claim with --all.
    Release {
        /// Service label to release.
        service: Option<String>,
        /// Release every claim in the registry.
        #[arg(long)]
        all: bool,
    },
    /// Show all claims and listening status.
    List {
        /// Emit the claim list as JSON.
        #[arg(long)]
        json: bool,
    },
    /// Reclaim stale claims.
    Gc {
        /// SQLite datetime modifier, for example '-7 days'.
        #[arg(long, value_name = "duration", default_value = "-7 days")]
        older_than: String,
        /// Show what would be reclaimed without changing anything.
        #[arg(long)]
        dry_run: bool,
    },
    /// Write the floo instruction into ~/.claude/CLAUDE.md.
    AgentSetup,
    /// Print floo version.
    Version,
    /// Print a shell completion script (bash, zsh, fish).
    Completions {
        /// Shell to generate completions for.
        shell: Shell,
    },
}

fn main() -> ExitCode {
    // Override only the root command's help so `floo`, `floo -h`, and
    // `floo --help` render TOP_HELP, while each subcommand keeps its own
    // clap-generated, tailored help.
    let mut cmd = Cli::command().override_help(TOP_HELP);
    let matches = match cmd.try_get_matches_from_mut(std::env::args_os()) {
        Ok(m) => m,
        Err(err) => return handle_clap_error(err),
    };
    let cli = Cli::from_arg_matches(&matches).expect("clap matches should deserialize into Cli");
    ExitCode::from(run(cli) as u8)
}

/// Translate a clap parse error into floo's exit-code and message contract.
fn handle_clap_error(err: clap::Error) -> ExitCode {
    match err.kind() {
        // Help and version are not errors: clap renders them to stdout, exit 0.
        ErrorKind::DisplayHelp | ErrorKind::DisplayVersion => {
            let _ = err.print();
            ExitCode::from(0)
        }
        // Preserve the historical "Unknown command: <name>" message and exit 2.
        ErrorKind::InvalidSubcommand => {
            eprintln!("Unknown command: {}", invalid_subcommand_name(&err));
            ExitCode::from(2)
        }
        // Any other usage error keeps clap's own message and exit code.
        _ => {
            let _ = err.print();
            ExitCode::from(err.exit_code() as u8)
        }
    }
}

/// Extract the offending subcommand token from a clap InvalidSubcommand error.
fn invalid_subcommand_name(err: &clap::Error) -> String {
    match err.get(ContextKind::InvalidSubcommand) {
        Some(ContextValue::String(s)) => s.clone(),
        _ => String::new(),
    }
}

fn run(cli: Cli) -> i32 {
    let db_override = cli.db.as_deref();
    match cli.command {
        None => {
            println!("{TOP_HELP}");
            0
        }
        Some(Command::List { json }) => cmd_list(json, db_override),
        Some(Command::Claim {
            service,
            prefer,
            json,
        }) => cmd_claim(service, prefer, json, db_override),
        Some(Command::Release { service, all }) => cmd_release(service, all, db_override),
        Some(Command::Gc {
            older_than,
            dry_run,
        }) => cmd_gc(&older_than, dry_run, db_override),
        Some(Command::AgentSetup) => cmd_agent_setup(),
        Some(Command::Version) => {
            println!("floo {VERSION}");
            0
        }
        Some(Command::Completions { shell }) => cmd_completions(shell),
    }
}

fn open_db(db_override: Option<&str>) -> Result<rusqlite::Connection, FlooError> {
    let path = paths::db_path_with_override(db_override)?;
    registry::connect(&path)
}

fn current_repo_path() -> Result<String, FlooError> {
    let p = paths::repo_root()?;
    Ok(p.to_string_lossy().into_owned())
}

// ---------------------------------------------------------------------------
// command handlers
// ---------------------------------------------------------------------------

fn cmd_list(json: bool, db_override: Option<&str>) -> i32 {
    let conn = match open_db(db_override) {
        Ok(c) => c,
        Err(e) => return fail(&e),
    };
    let claims = match registry::list_claims(&conn) {
        Ok(c) => c,
        Err(e) => return fail(&e),
    };
    if json {
        let entries: Vec<ListEntryJson> = claims
            .iter()
            .map(|c| ListEntryJson {
                claim: c,
                listening: !scanner::is_port_free_on_os(c.port),
            })
            .collect();
        println!("{}", serde_json::to_string_pretty(&entries).unwrap());
        return 0;
    }
    if claims.is_empty() {
        println!("No claims yet. Run `floo claim <service>` in a repo to make one.");
        return 0;
    }
    println!("{:<6} {:<10} {:<14} REPO", "PORT", "LISTENING", "SERVICE");
    for c in &claims {
        let listening = if scanner::is_port_free_on_os(c.port) {
            "no"
        } else {
            "yes"
        };
        println!(
            "{:<6} {:<10} {:<14} {}",
            c.port, listening, c.service, c.repo_path
        );
    }
    0
}

fn cmd_claim(
    service: Option<String>,
    prefer: Option<u16>,
    json: bool,
    db_override: Option<&str>,
) -> i32 {
    let Some(service) = service else {
        return print_claim_usage_with_state(db_override);
    };

    let rp = match current_repo_path() {
        Ok(rp) => rp,
        Err(e) => return fail(&e),
    };
    let conn = match open_db(db_override) {
        Ok(c) => c,
        Err(e) => return fail(&e),
    };
    match registry::claim(&conn, &rp, &service, prefer) {
        Ok(result) => {
            if json {
                let out = ClaimJson {
                    claim: &result.claim,
                    was_new: result.was_new,
                };
                println!("{}", serde_json::to_string_pretty(&out).unwrap());
            } else {
                println!("{}", result.claim.port);
            }
            0
        }
        Err(e) => fail(&e),
    }
}

fn cmd_release(service: Option<String>, all: bool, db_override: Option<&str>) -> i32 {
    let conn = match open_db(db_override) {
        Ok(c) => c,
        Err(e) => return fail(&e),
    };

    if all {
        return match registry::release_all(&conn) {
            Ok(n) => {
                println!("Released {n} claim(s).");
                0
            }
            Err(e) => fail(&e),
        };
    }

    let Some(service) = service else {
        return print_release_usage_with_state(db_override);
    };

    let rp = match current_repo_path() {
        Ok(rp) => rp,
        Err(e) => return fail(&e),
    };

    match registry::release(&conn, &rp, &service) {
        Ok(true) => {
            println!("Released {service}.");
            0
        }
        Ok(false) => {
            eprintln!("No claim for service '{service}' in this repo.");
            1
        }
        Err(e) => fail(&e),
    }
}

fn cmd_gc(older_than: &str, dry_run: bool, db_override: Option<&str>) -> i32 {
    let conn = match open_db(db_override) {
        Ok(c) => c,
        Err(e) => return fail(&e),
    };
    let cands = match registry::gc(&conn, older_than, dry_run) {
        Ok(c) => c,
        Err(e) => return fail(&e),
    };
    if cands.is_empty() {
        println!("Nothing to reclaim.");
        return 0;
    }
    let verb = if dry_run {
        "Would reclaim"
    } else {
        "Reclaimed"
    };
    for c in &cands {
        println!(
            "{verb}: port {} ({} @ {}) - {}",
            c.claim.port, c.claim.service, c.claim.repo_path, c.reason
        );
    }
    0
}

fn cmd_agent_setup() -> i32 {
    let target = match agent_setup::claude_md_path() {
        Ok(p) => p,
        Err(e) => {
            eprintln!("{e}");
            return 1;
        }
    };
    match agent_setup::install(&target) {
        Ok((path, action)) => {
            let mut chars = action.chars();
            let capitalized = match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => action,
            };
            println!("{capitalized} floo block in {}", path.display());
            0
        }
        Err(e) => {
            eprintln!("{e}");
            1
        }
    }
}

fn cmd_completions(shell: Shell) -> i32 {
    let mut cmd = Cli::command();
    clap_complete::generate(shell, &mut cmd, "floo", &mut io::stdout());
    0
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

fn print_claim_usage_with_state(db_override: Option<&str>) -> i32 {
    println!("usage: floo claim <service> [--prefer PORT]");
    let rp = match current_repo_path() {
        Ok(rp) => rp,
        Err(e) => return fail(&e),
    };
    let conn = match open_db(db_override) {
        Ok(c) => c,
        Err(e) => return fail(&e),
    };
    let existing: Vec<registry::Claim> = match registry::list_claims(&conn) {
        Ok(c) => c.into_iter().filter(|c| c.repo_path == rp).collect(),
        Err(e) => return fail(&e),
    };
    if existing.is_empty() {
        println!("\nNo claims yet in {rp}.");
    } else {
        println!("\nExisting claims in {rp}:");
        for c in &existing {
            println!("  {:<14} port {}", c.service, c.port);
        }
    }
    0
}

fn print_release_usage_with_state(db_override: Option<&str>) -> i32 {
    println!("usage: floo release <service> | --all");
    let rp = match current_repo_path() {
        Ok(rp) => rp,
        Err(e) => return fail(&e),
    };
    let conn = match open_db(db_override) {
        Ok(c) => c,
        Err(e) => return fail(&e),
    };
    let existing: Vec<registry::Claim> = match registry::list_claims(&conn) {
        Ok(c) => c.into_iter().filter(|c| c.repo_path == rp).collect(),
        Err(e) => return fail(&e),
    };
    if existing.is_empty() {
        println!("\nNo claims to release in {rp}.");
    } else {
        println!("\nReleasable services in {rp}:");
        for c in &existing {
            println!("  {:<14} port {}", c.service, c.port);
        }
    }
    0
}

fn fail(e: &FlooError) -> i32 {
    eprintln!("{e}");
    1
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_claim_json_shape() {
        let claim = registry::Claim {
            repo_path: "/repo/A".to_string(),
            service: "web".to_string(),
            port: 3000,
            created_at: "2026-07-04T12:00:00Z".to_string(),
            last_seen_listening: None,
        };
        let out = ClaimJson {
            claim: &claim,
            was_new: true,
        };
        let v: serde_json::Value =
            serde_json::from_str(&serde_json::to_string(&out).unwrap()).unwrap();
        assert_eq!(v["repo_path"], "/repo/A");
        assert_eq!(v["service"], "web");
        assert_eq!(v["port"], 3000);
        assert_eq!(v["created_at"], "2026-07-04T12:00:00Z");
        assert!(v["last_seen_listening"].is_null());
        assert_eq!(v["was_new"], true);
    }

    #[test]
    fn test_list_entry_json_shape() {
        let claim = registry::Claim {
            repo_path: "/repo/A".to_string(),
            service: "web".to_string(),
            port: 3001,
            created_at: "2026-07-04T12:00:00Z".to_string(),
            last_seen_listening: Some("2026-07-04T13:00:00Z".to_string()),
        };
        let out = ListEntryJson {
            claim: &claim,
            listening: true,
        };
        let v: serde_json::Value =
            serde_json::from_str(&serde_json::to_string(&out).unwrap()).unwrap();
        assert_eq!(v["port"], 3001);
        assert_eq!(v["last_seen_listening"], "2026-07-04T13:00:00Z");
        assert_eq!(v["listening"], true);
    }

    #[test]
    fn test_cli_verifies() {
        Cli::command().debug_assert();
    }
}
