//! SQLite-backed claim registry.
//!
//! One row = one active claim (a (repo_path, service) pair holding a port).
//!
//! Key design decisions:
//!   - Primary key is (repo_path, service): that's the natural lookup pattern.
//!   - port is UNIQUE: schema-level safety net against double-allocation bugs.
//!   - Timestamps are ISO 8601 text, generated by SQLite's strftime so they
//!     stay consistent with SQLite's own clock and format.
//!   - All mutating operations run inside a BEGIN IMMEDIATE transaction. That
//!     grabs the SQLite write lock up front, so the read-decide-write
//!     sequence is atomic across agents racing in parallel.

use std::fmt;
use std::path::Path;

use rusqlite::{Connection, OptionalExtension};

use crate::scanner::is_port_free_on_os;

/// v1 port range. 3000 is the common dev-server default; staying in 3xxx
/// keeps us clear of OS reserved ports and ephemeral ranges. Hit the ceiling,
/// error.
pub const PORT_MIN: u16 = 3000;
pub const PORT_MAX: u16 = 3999;

const SCHEMA: &str = "
CREATE TABLE IF NOT EXISTS claims (
    repo_path           TEXT    NOT NULL,
    service             TEXT    NOT NULL,
    port                INTEGER NOT NULL UNIQUE,
    created_at          TEXT    NOT NULL,
    last_seen_listening TEXT,
    PRIMARY KEY (repo_path, service)
);
";

#[derive(Debug)]
pub enum FlooError {
    Sqlite(rusqlite::Error),
    NoFreePort,
    Io(std::io::Error),
}

impl fmt::Display for FlooError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            FlooError::Sqlite(e) => write!(f, "{e}"),
            FlooError::NoFreePort => write!(
                f,
                "No free port in {PORT_MIN}-{PORT_MAX}. Run `floo gc` to reclaim stale claims."
            ),
            FlooError::Io(e) => write!(f, "{e}"),
        }
    }
}

impl std::error::Error for FlooError {}

impl From<rusqlite::Error> for FlooError {
    fn from(e: rusqlite::Error) -> Self {
        FlooError::Sqlite(e)
    }
}

impl From<std::io::Error> for FlooError {
    fn from(e: std::io::Error) -> Self {
        FlooError::Io(e)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize)]
pub struct Claim {
    pub repo_path: String,
    pub service: String,
    pub port: u16,
    pub created_at: String,
    pub last_seen_listening: Option<String>,
}

#[derive(Debug, Clone)]
pub struct ClaimResult {
    pub claim: Claim,
    /// True if we allocated a new row, false if we returned an existing one.
    pub was_new: bool,
}

#[derive(Debug, Clone)]
pub struct GcCandidate {
    pub claim: Claim,
    /// Human-readable: why it's eligible.
    pub reason: String,
}

/// Open a connection to the registry at `path`, set required pragmas, and
/// ensure the schema exists.
pub fn connect(path: &Path) -> Result<Connection, FlooError> {
    let conn = Connection::open(path)?;
    conn.pragma_update(None, "journal_mode", "WAL")?;
    conn.pragma_update(None, "busy_timeout", 5000)?;
    conn.execute_batch(SCHEMA)?;
    Ok(conn)
}

fn now_iso(conn: &Connection) -> Result<String, FlooError> {
    let ts: String = conn.query_row("SELECT strftime('%Y-%m-%dT%H:%M:%SZ','now')", [], |row| {
        row.get(0)
    })?;
    Ok(ts)
}

fn row_to_claim(row: &rusqlite::Row) -> rusqlite::Result<Claim> {
    Ok(Claim {
        repo_path: row.get("repo_path")?,
        service: row.get("service")?,
        port: row.get("port")?,
        created_at: row.get("created_at")?,
        last_seen_listening: row.get("last_seen_listening")?,
    })
}

// ---------------------------------------------------------------------------
// claim
// ---------------------------------------------------------------------------

/// Get or allocate a port for (repo_path, service).
///
/// Idempotent: calling twice returns the same port and was_new=false the
/// second time.
pub fn claim(
    conn: &Connection,
    repo_path: &str,
    service: &str,
    prefer: Option<u16>,
) -> Result<ClaimResult, FlooError> {
    conn.execute_batch("BEGIN IMMEDIATE")?;

    let result = (|| -> Result<ClaimResult, FlooError> {
        let existing = conn
            .query_row(
                "SELECT * FROM claims WHERE repo_path = ?1 AND service = ?2",
                (repo_path, service),
                row_to_claim,
            )
            .optional()?;

        if let Some(existing) = existing {
            return Ok(ClaimResult {
                claim: existing,
                was_new: false,
            });
        }

        let port = pick_port(conn, prefer)?;
        let now = now_iso(conn)?;
        conn.execute(
            "INSERT INTO claims (repo_path, service, port, created_at, last_seen_listening) \
             VALUES (?1, ?2, ?3, ?4, NULL)",
            (repo_path, service, port, &now),
        )?;

        Ok(ClaimResult {
            claim: Claim {
                repo_path: repo_path.to_string(),
                service: service.to_string(),
                port,
                created_at: now,
                last_seen_listening: None,
            },
            was_new: true,
        })
    })();

    match result {
        Ok(r) => {
            conn.execute_batch("COMMIT")?;
            Ok(r)
        }
        Err(e) => {
            let _ = conn.execute_batch("ROLLBACK");
            Err(e)
        }
    }
}

/// Inside an open transaction, find an unused port.
///
/// A port is "free" iff: not in the registry AND not bound by an OS process.
fn pick_port(conn: &Connection, prefer: Option<u16>) -> Result<u16, FlooError> {
    let mut stmt = conn.prepare("SELECT port FROM claims")?;
    let taken: std::collections::HashSet<u16> = stmt
        .query_map([], |row| row.get::<_, i64>(0))?
        .filter_map(|r| r.ok())
        .map(|p| p as u16)
        .collect();
    drop(stmt);

    if let Some(prefer) = prefer {
        if (PORT_MIN..=PORT_MAX).contains(&prefer)
            && !taken.contains(&prefer)
            && is_port_free_on_os(prefer)
        {
            return Ok(prefer);
        }
    }

    for candidate in PORT_MIN..=PORT_MAX {
        if taken.contains(&candidate) {
            continue;
        }
        if !is_port_free_on_os(candidate) {
            continue;
        }
        return Ok(candidate);
    }

    Err(FlooError::NoFreePort)
}

// ---------------------------------------------------------------------------
// release
// ---------------------------------------------------------------------------

/// Release a single claim. Returns true if a row was removed.
pub fn release(conn: &Connection, repo_path: &str, service: &str) -> Result<bool, FlooError> {
    let n = conn.execute(
        "DELETE FROM claims WHERE repo_path = ?1 AND service = ?2",
        (repo_path, service),
    )?;
    Ok(n > 0)
}

/// Release every claim. Returns number removed.
pub fn release_all(conn: &Connection) -> Result<usize, FlooError> {
    let n = conn.execute("DELETE FROM claims", [])?;
    Ok(n)
}

// ---------------------------------------------------------------------------
// list
// ---------------------------------------------------------------------------

/// Return all claims, ordered by port. Pure read, never mutates.
pub fn list_claims(conn: &Connection) -> Result<Vec<Claim>, FlooError> {
    let mut stmt = conn.prepare("SELECT * FROM claims ORDER BY port")?;
    let rows = stmt
        .query_map([], row_to_claim)?
        .collect::<rusqlite::Result<Vec<_>>>()?;
    Ok(rows)
}

// ---------------------------------------------------------------------------
// gc
// ---------------------------------------------------------------------------

/// Find claims eligible for reclamation.
///
/// A claim is eligible if it has not been observed listening recently. The
/// `older_than` argument is SQLite-modifier syntax (e.g., '-7 days').
///
/// Callers must run this inside a transaction if they intend to act on the
/// results and then delete rows, since the OS re-probe here may itself
/// mutate `last_seen_listening`.
pub fn find_gc_candidates(
    conn: &Connection,
    older_than: &str,
) -> Result<Vec<GcCandidate>, FlooError> {
    let mut stmt = conn.prepare(
        "SELECT * FROM claims WHERE \
         (last_seen_listening IS NOT NULL \
          AND datetime(last_seen_listening) < datetime('now', ?1)) \
         OR (last_seen_listening IS NULL \
          AND datetime(created_at) < datetime('now', ?1))",
    )?;
    let rows = stmt
        .query_map([older_than], row_to_claim)?
        .collect::<rusqlite::Result<Vec<_>>>()?;
    drop(stmt);

    let mut out = Vec::new();
    for c in rows {
        // Re-probe at gc time. If a server is actively listening right now,
        // refuse to reclaim regardless of the stale timestamp.
        if !is_port_free_on_os(c.port) {
            let now = now_iso(conn)?;
            conn.execute(
                "UPDATE claims SET last_seen_listening = ?1 \
                 WHERE repo_path = ?2 AND service = ?3",
                (&now, &c.repo_path, &c.service),
            )?;
            continue;
        }
        let reason = match &c.last_seen_listening {
            None => "never seen listening".to_string(),
            Some(ts) => format!("last listening at {ts}"),
        };
        out.push(GcCandidate { claim: c, reason });
    }
    Ok(out)
}

/// Reclaim stale claims. Returns the list of (would-be-)reclaimed rows.
pub fn gc(
    conn: &Connection,
    older_than: &str,
    dry_run: bool,
) -> Result<Vec<GcCandidate>, FlooError> {
    conn.execute_batch("BEGIN IMMEDIATE")?;

    let result = (|| -> Result<Vec<GcCandidate>, FlooError> {
        let candidates = find_gc_candidates(conn, older_than)?;
        if !dry_run {
            for cand in &candidates {
                conn.execute(
                    "DELETE FROM claims WHERE repo_path = ?1 AND service = ?2",
                    (&cand.claim.repo_path, &cand.claim.service),
                )?;
            }
        }
        Ok(candidates)
    })();

    match result {
        Ok(r) => {
            conn.execute_batch("COMMIT")?;
            Ok(r)
        }
        Err(e) => {
            let _ = conn.execute_batch("ROLLBACK");
            Err(e)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    fn temp_conn() -> (tempfile::TempDir, Connection) {
        let dir = tempdir().unwrap();
        let path = dir.path().join("registry.db");
        let conn = connect(&path).unwrap();
        (dir, conn)
    }

    #[test]
    fn test_claim_is_idempotent() {
        let (_dir, conn) = temp_conn();
        let r1 = claim(&conn, "/repo/A", "web", None).unwrap();
        let r2 = claim(&conn, "/repo/A", "web", None).unwrap();
        assert_eq!(r1.claim.port, r2.claim.port);
        assert!(r1.was_new);
        assert!(!r2.was_new);
    }

    #[test]
    fn test_distinct_repo_and_service_get_distinct_ports() {
        let (_dir, conn) = temp_conn();
        let p_a = claim(&conn, "/repo/A", "web", None).unwrap().claim.port;
        let p_b = claim(&conn, "/repo/B", "web", None).unwrap().claim.port;
        let p_c = claim(&conn, "/repo/A", "storybook", None)
            .unwrap()
            .claim
            .port;
        let set: std::collections::HashSet<u16> = [p_a, p_b, p_c].into_iter().collect();
        assert_eq!(set.len(), 3);
    }

    #[test]
    fn test_release_then_reclaim() {
        let (_dir, conn) = temp_conn();
        let _p1 = claim(&conn, "/repo/A", "web", None).unwrap().claim.port;
        assert!(release(&conn, "/repo/A", "web").unwrap());
        let r2 = claim(&conn, "/repo/A", "web", None).unwrap();
        assert!(r2.was_new);
    }

    #[test]
    fn test_release_all() {
        let (_dir, conn) = temp_conn();
        claim(&conn, "/repo/A", "web", None).unwrap();
        claim(&conn, "/repo/B", "web", None).unwrap();
        assert_eq!(release_all(&conn).unwrap(), 2);
        assert!(list_claims(&conn).unwrap().is_empty());
    }

    #[test]
    fn test_gc_reclaims_never_seen() {
        let (_dir, conn) = temp_conn();
        claim(&conn, "/repo/A", "web", None).unwrap();
        // "-0 seconds" is not reliably "earlier than now" once created_at and
        // the gc probe land in the same wall-clock second (equal, not less
        // than, at whole-second resolution). "+1 seconds" pushes the
        // threshold one second past "now", so created_at (set moments ago)
        // is deterministically earlier than it, forcing immediate
        // eligibility while exercising the same comparison codepath.
        let cands = gc(&conn, "+1 seconds", false).unwrap();
        assert_eq!(cands.len(), 1);
        assert_eq!(cands[0].claim.service, "web");
        assert!(list_claims(&conn).unwrap().is_empty());
    }
}
